name: 'Update Data'

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Install tesseract
        run: |
          sudo apt update
          sudo apt install -y tesseract-ocr libtesseract-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Update data to latest
        env:
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        run: |
          python updater.py
      - name: Get current date
        id: date
        run: echo ::set-output name=today::$(date +'%Y-%m-%dT%H:%M:%SZ')
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data ${{ steps.date.outputs.today }}