name: 'Update Data'

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt install -y tesseract-ocr libtesseract-dev
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Update data to latest
        env:
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        run: |
          python updater.py
      - name: Set current date as env variable
        id: date
        run: echo ::set-output name=today::$(date +'%Y-%m-%dT%H:%M:%SZ')
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data ${{ steps.date.outputs.today }}